// web/src/features/games/mahjong/constants/yaku-guide.ts

export type YakuGuideCategory = "NORMAL" | "SITUATIONAL";
export type YakuGuideOpenType = "MENZEN_ONLY" | "OPEN_ALLOWED";

export type YakuGuideItem = {
    id: string;
    name: string;
    japaneseName: string;
    category: YakuGuideCategory;
    closedHan: number;
    openHan: number;
    isYakuman?: boolean;
    yakumanMultiplier?: number;
    openType: YakuGuideOpenType;
    description: string;
    exampleTiles: string[];
    notes?: string[];
};

export const YAKU_GUIDE_ITEMS: YakuGuideItem[] = [
    {
        id: "riichi",
        name: "리치",
        japaneseName: "立直",
        category: "SITUATIONAL",
        closedHan: 1,
        openHan: 0,
        openType: "MENZEN_ONLY",
        description: "멘젠 상태에서 텐파이 후 리치를 선언하면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀈",
            "🀉",
            "🀋",
            "🀌",
            "🀍",
            "🀙",
            "🀚",
            "🀛",
            "🀐",
            "🀑",
            "🀒",
            "🀀",
            "🀀",
        ],
        notes: [
            "후로한 상태에서는 선언할 수 없습니다.",
            "리치 선언 시 1,000점 공탁을 냅니다.",
        ],
    },
    {
        id: "double_riichi",
        name: "더블 리치",
        japaneseName: "両立直",
        category: "SITUATIONAL",
        closedHan: 2,
        openHan: 0,
        openType: "MENZEN_ONLY",
        description: "첫 순에 아무 부름 없이 리치를 선언하면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀈",
            "🀉",
            "🀋",
            "🀌",
            "🀍",
            "🀙",
            "🀚",
            "🀛",
            "🀐",
            "🀑",
            "🀒",
            "🀀",
            "🀀",
        ],
        notes: ["일반 리치와 중복되지 않습니다."],
    },
    {
        id: "menzen_tsumo",
        name: "멘젠쯔모",
        japaneseName: "門前清自摸和",
        category: "SITUATIONAL",
        closedHan: 1,
        openHan: 0,
        openType: "MENZEN_ONLY",
        description: "멘젠 상태에서 쯔모로 화료하면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀈",
            "🀉",
            "🀋",
            "🀌",
            "🀍",
            "🀙",
            "🀚",
            "🀛",
            "🀐",
            "🀑",
            "🀒",
            "🀀",
            "🀀",
        ],
    },
    {
        id: "ippatsu",
        name: "일발",
        japaneseName: "一発",
        category: "SITUATIONAL",
        closedHan: 1,
        openHan: 0,
        openType: "MENZEN_ONLY",
        description: "리치 후 한 순 안에 아무 부름 없이 화료하면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀈",
            "🀉",
            "🀋",
            "🀌",
            "🀍",
            "🀙",
            "🀚",
            "🀛",
            "🀐",
            "🀑",
            "🀒",
            "🀀",
            "🀀",
        ],
    },
    {
        id: "rinshan",
        name: "영상개화",
        japaneseName: "嶺上開花",
        category: "SITUATIONAL",
        closedHan: 1,
        openHan: 1,
        openType: "OPEN_ALLOWED",
        description: "깡을 한 뒤 영상패로 쯔모 화료하면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀇",
            "🀇",
            "🀇",
            "🀋",
            "🀌",
            "🀍",
            "🀙",
            "🀚",
            "🀛",
            "🀐",
            "🀑",
            "🀒",
            "🀀",
        ],
    },
    {
        id: "chankan",
        name: "창깡",
        japaneseName: "槍槓",
        category: "SITUATIONAL",
        closedHan: 1,
        openHan: 1,
        openType: "OPEN_ALLOWED",
        description: "상대가 가깡을 할 때 그 패로 론 화료하면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀈",
            "🀉",
            "🀋",
            "🀌",
            "🀍",
            "🀙",
            "🀚",
            "🀛",
            "🀐",
            "🀑",
            "🀒",
            "🀀",
            "🀀",
        ],
    },
    {
        id: "haitei",
        name: "해저로월",
        japaneseName: "海底撈月",
        category: "SITUATIONAL",
        closedHan: 1,
        openHan: 1,
        openType: "OPEN_ALLOWED",
        description: "마지막 쯔모패로 화료하면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀈",
            "🀉",
            "🀋",
            "🀌",
            "🀍",
            "🀙",
            "🀚",
            "🀛",
            "🀐",
            "🀑",
            "🀒",
            "🀀",
            "🀀",
        ],
    },
    {
        id: "houtei",
        name: "하저로어",
        japaneseName: "河底撈魚",
        category: "SITUATIONAL",
        closedHan: 1,
        openHan: 1,
        openType: "OPEN_ALLOWED",
        description: "마지막 버림패로 론 화료하면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀈",
            "🀉",
            "🀋",
            "🀌",
            "🀍",
            "🀙",
            "🀚",
            "🀛",
            "🀐",
            "🀑",
            "🀒",
            "🀀",
            "🀀",
        ],
    },

    {
        id: "tanyao",
        name: "탕야오",
        japaneseName: "断么九",
        category: "NORMAL",
        closedHan: 1,
        openHan: 1,
        openType: "OPEN_ALLOWED",
        description:
            "2~8의 수패만으로 화료하면 성립합니다. 1, 9, 자패가 있으면 성립하지 않습니다.",
        exampleTiles: [
            "🀈",
            "🀉",
            "🀊",
            "🀌",
            "🀍",
            "🀎",
            "🀚",
            "🀛",
            "🀜",
            "🀑",
            "🀒",
            "🀓",
            "🀋",
            "🀋",
        ],
    },
    {
        id: "yakuhai_dragon_white",
        name: "역패 백",
        japaneseName: "白",
        category: "NORMAL",
        closedHan: 1,
        openHan: 1,
        openType: "OPEN_ALLOWED",
        description: "백패를 커쯔 또는 깡쯔로 만들면 성립합니다.",
        exampleTiles: [
            "🀆",
            "🀆",
            "🀆",
            "🀇",
            "🀈",
            "🀉",
            "🀋",
            "🀌",
            "🀍",
            "🀙",
            "🀚",
            "🀛",
            "🀀",
            "🀀",
        ],
    },
    {
        id: "yakuhai_dragon_green",
        name: "역패 발",
        japaneseName: "發",
        category: "NORMAL",
        closedHan: 1,
        openHan: 1,
        openType: "OPEN_ALLOWED",
        description: "발패를 커쯔 또는 깡쯔로 만들면 성립합니다.",
        exampleTiles: [
            "🀅",
            "🀅",
            "🀅",
            "🀇",
            "🀈",
            "🀉",
            "🀋",
            "🀌",
            "🀍",
            "🀙",
            "🀚",
            "🀛",
            "🀀",
            "🀀",
        ],
    },
    {
        id: "yakuhai_dragon_red",
        name: "역패 중",
        japaneseName: "中",
        category: "NORMAL",
        closedHan: 1,
        openHan: 1,
        openType: "OPEN_ALLOWED",
        description: "중패를 커쯔 또는 깡쯔로 만들면 성립합니다.",
        exampleTiles: [
            "🀄",
            "🀄",
            "🀄",
            "🀇",
            "🀈",
            "🀉",
            "🀋",
            "🀌",
            "🀍",
            "🀙",
            "🀚",
            "🀛",
            "🀀",
            "🀀",
        ],
    },
    {
        id: "yakuhai_prevailing",
        name: "장풍패",
        japaneseName: "場風牌",
        category: "NORMAL",
        closedHan: 1,
        openHan: 1,
        openType: "OPEN_ALLOWED",
        description: "현재 장의 바람패를 커쯔 또는 깡쯔로 만들면 성립합니다.",
        exampleTiles: [
            "🀀",
            "🀀",
            "🀀",
            "🀇",
            "🀈",
            "🀉",
            "🀋",
            "🀌",
            "🀍",
            "🀙",
            "🀚",
            "🀛",
            "🀆",
            "🀆",
        ],
    },
    {
        id: "yakuhai_player",
        name: "자풍패",
        japaneseName: "自風牌",
        category: "NORMAL",
        closedHan: 1,
        openHan: 1,
        openType: "OPEN_ALLOWED",
        description: "내 자리의 바람패를 커쯔 또는 깡쯔로 만들면 성립합니다.",
        exampleTiles: [
            "🀀",
            "🀀",
            "🀀",
            "🀇",
            "🀈",
            "🀉",
            "🀋",
            "🀌",
            "🀍",
            "🀙",
            "🀚",
            "🀛",
            "🀆",
            "🀆",
        ],
    },
    {
        id: "pinfu",
        name: "핑후",
        japaneseName: "平和",
        category: "NORMAL",
        closedHan: 1,
        openHan: 0,
        openType: "MENZEN_ONLY",
        description:
            "부수가 붙지 않는 형태의 멘젠 화료입니다. 일반적으로 슌쯔 4개, 역패가 아닌 머리, 양면 대기 형태가 필요합니다.",
        exampleTiles: [
            "🀇",
            "🀈",
            "🀉",
            "🀋",
            "🀌",
            "🀍",
            "🀙",
            "🀚",
            "🀛",
            "🀐",
            "🀑",
            "🀒",
            "🀆",
            "🀆",
        ],
        notes: ["멘젠 론이면 30부, 멘젠 쯔모면 보통 20부로 계산합니다."],
    },
    {
        id: "iipeikou",
        name: "이페코",
        japaneseName: "一盃口",
        category: "NORMAL",
        closedHan: 1,
        openHan: 0,
        openType: "MENZEN_ONLY",
        description: "같은 수패의 같은 슌쯔 2개가 있으면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀈",
            "🀉",
            "🀇",
            "🀈",
            "🀉",
            "🀙",
            "🀚",
            "🀛",
            "🀐",
            "🀑",
            "🀒",
            "🀀",
            "🀀",
        ],
    },

    {
        id: "sanshoku",
        name: "삼색동순",
        japaneseName: "三色同順",
        category: "NORMAL",
        closedHan: 2,
        openHan: 1,
        openType: "OPEN_ALLOWED",
        description:
            "만수, 통수, 삭수에서 같은 숫자 배열의 슌쯔를 각각 하나씩 만들면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀈",
            "🀉",
            "🀙",
            "🀚",
            "🀛",
            "🀐",
            "🀑",
            "🀒",
            "🀋",
            "🀌",
            "🀍",
            "🀀",
            "🀀",
        ],
        notes: ["후로하면 1판으로 내려갑니다."],
    },
    {
        id: "ittsuu",
        name: "일기통관",
        japaneseName: "一気通貫",
        category: "NORMAL",
        closedHan: 2,
        openHan: 1,
        openType: "OPEN_ALLOWED",
        description: "한 종류의 수패로 123, 456, 789 슌쯔를 모두 만들면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀈",
            "🀉",
            "🀊",
            "🀋",
            "🀌",
            "🀍",
            "🀎",
            "🀏",
            "🀙",
            "🀚",
            "🀛",
            "🀀",
            "🀀",
        ],
        notes: ["후로하면 1판으로 내려갑니다."],
    },
    {
        id: "chanta",
        name: "찬타",
        japaneseName: "混全帯么九",
        category: "NORMAL",
        closedHan: 2,
        openHan: 1,
        openType: "OPEN_ALLOWED",
        description:
            "모든 몸통과 머리에 1, 9 또는 자패가 포함되며, 슌쯔가 하나 이상 있으면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀈",
            "🀉",
            "🀍",
            "🀎",
            "🀏",
            "🀀",
            "🀀",
            "🀀",
            "🀆",
            "🀆",
            "🀆",
            "🀄",
            "🀄",
        ],
        notes: ["후로하면 1판으로 내려갑니다."],
    },
    {
        id: "chiitoitsu",
        name: "치또이쯔",
        japaneseName: "七対子",
        category: "NORMAL",
        closedHan: 2,
        openHan: 0,
        openType: "MENZEN_ONLY",
        description: "서로 다른 또이쯔 7개로 화료하면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀇",
            "🀉",
            "🀉",
            "🀋",
            "🀋",
            "🀙",
            "🀙",
            "🀛",
            "🀛",
            "🀀",
            "🀀",
            "🀄",
            "🀄",
        ],
        notes: ["치또이쯔는 25부 고정입니다."],
    },
    {
        id: "toitoi",
        name: "또이또이",
        japaneseName: "対々和",
        category: "NORMAL",
        closedHan: 2,
        openHan: 2,
        openType: "OPEN_ALLOWED",
        description: "모든 몸통을 커쯔 또는 깡쯔로 만들면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀇",
            "🀇",
            "🀙",
            "🀙",
            "🀙",
            "🀐",
            "🀐",
            "🀐",
            "🀄",
            "🀄",
            "🀄",
            "🀀",
            "🀀",
        ],
    },
    {
        id: "sanshoku_doukou",
        name: "삼색동각",
        japaneseName: "三色同刻",
        category: "NORMAL",
        closedHan: 2,
        openHan: 2,
        openType: "OPEN_ALLOWED",
        description:
            "만수, 통수, 삭수에서 같은 숫자의 커쯔를 각각 하나씩 만들면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀇",
            "🀇",
            "🀙",
            "🀙",
            "🀙",
            "🀐",
            "🀐",
            "🀐",
            "🀋",
            "🀌",
            "🀍",
            "🀀",
            "🀀",
        ],
    },
    {
        id: "sankantsu",
        name: "산깡쯔",
        japaneseName: "三槓子",
        category: "NORMAL",
        closedHan: 2,
        openHan: 2,
        openType: "OPEN_ALLOWED",
        description: "깡쯔를 3개 만들면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀇",
            "🀇",
            "🀇",
            "🀙",
            "🀙",
            "🀙",
            "🀙",
            "🀐",
            "🀐",
            "🀐",
            "🀐",
            "🀀",
            "🀀",
        ],
    },
    {
        id: "sanankou",
        name: "산안커",
        japaneseName: "三暗刻",
        category: "NORMAL",
        closedHan: 2,
        openHan: 2,
        openType: "OPEN_ALLOWED",
        description: "안커를 3개 만들면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀇",
            "🀇",
            "🀙",
            "🀙",
            "🀙",
            "🀐",
            "🀐",
            "🀐",
            "🀋",
            "🀌",
            "🀍",
            "🀀",
            "🀀",
        ],
        notes: ["론으로 만든 마지막 커쯔는 안커로 보지 않는 경우가 많습니다."],
    },
    {
        id: "shousangen",
        name: "소삼원",
        japaneseName: "小三元",
        category: "NORMAL",
        closedHan: 2,
        openHan: 2,
        openType: "OPEN_ALLOWED",
        description:
            "삼원패 중 2종류를 커쯔로 만들고, 나머지 1종류를 머리로 만들면 성립합니다.",
        exampleTiles: [
            "🀆",
            "🀆",
            "🀆",
            "🀅",
            "🀅",
            "🀅",
            "🀄",
            "🀄",
            "🀇",
            "🀈",
            "🀉",
            "🀙",
            "🀚",
            "🀛",
        ],
    },
    {
        id: "honroutou",
        name: "혼노두",
        japaneseName: "混老頭",
        category: "NORMAL",
        closedHan: 2,
        openHan: 2,
        openType: "OPEN_ALLOWED",
        description: "1, 9, 자패만으로 화료하면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀇",
            "🀇",
            "🀏",
            "🀏",
            "🀏",
            "🀀",
            "🀀",
            "🀀",
            "🀄",
            "🀄",
            "🀄",
            "🀆",
            "🀆",
        ],
    },

    {
        id: "junchan",
        name: "준찬타",
        japaneseName: "純全帯么九",
        category: "NORMAL",
        closedHan: 3,
        openHan: 2,
        openType: "OPEN_ALLOWED",
        description:
            "모든 몸통과 머리에 1 또는 9가 포함되며, 슌쯔가 하나 이상 있으면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀈",
            "🀉",
            "🀍",
            "🀎",
            "🀏",
            "🀙",
            "🀚",
            "🀛",
            "🀝",
            "🀞",
            "🀟",
            "🀇",
            "🀇",
        ],
        notes: ["후로하면 2판으로 내려갑니다."],
    },
    {
        id: "honitsu",
        name: "혼일색",
        japaneseName: "混一色",
        category: "NORMAL",
        closedHan: 3,
        openHan: 2,
        openType: "OPEN_ALLOWED",
        description: "한 종류의 수패와 자패만으로 화료하면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀈",
            "🀉",
            "🀋",
            "🀌",
            "🀍",
            "🀏",
            "🀏",
            "🀏",
            "🀀",
            "🀀",
            "🀀",
            "🀄",
            "🀄",
        ],
        notes: ["후로하면 2판으로 내려갑니다."],
    },
    {
        id: "ryanpeikou",
        name: "량페코",
        japaneseName: "二盃口",
        category: "NORMAL",
        closedHan: 3,
        openHan: 0,
        openType: "MENZEN_ONLY",
        description: "이페코 형태가 2쌍 있으면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀈",
            "🀉",
            "🀇",
            "🀈",
            "🀉",
            "🀙",
            "🀚",
            "🀛",
            "🀙",
            "🀚",
            "🀛",
            "🀀",
            "🀀",
        ],
    },

    {
        id: "chinitsu",
        name: "청일색",
        japaneseName: "清一色",
        category: "NORMAL",
        closedHan: 6,
        openHan: 5,
        openType: "OPEN_ALLOWED",
        description: "한 종류의 수패만으로 화료하면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀇",
            "🀈",
            "🀉",
            "🀊",
            "🀋",
            "🀌",
            "🀍",
            "🀎",
            "🀎",
            "🀎",
            "🀏",
            "🀏",
            "🀏",
        ],
        notes: ["후로하면 5판으로 내려갑니다."],
    },

    {
        id: "kokushi",
        name: "국사무쌍",
        japaneseName: "国士無双",
        category: "NORMAL",
        closedHan: 13,
        openHan: 0,
        isYakuman: true,
        yakumanMultiplier: 1,
        openType: "MENZEN_ONLY",
        description:
            "1, 9, 자패 13종을 모두 모으고 그중 하나를 머리로 만들면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀏",
            "🀙",
            "🀡",
            "🀐",
            "🀘",
            "🀀",
            "🀁",
            "🀂",
            "🀃",
            "🀆",
            "🀅",
            "🀄",
            "🀇",
        ],
    },
    {
        id: "kokushi_13_wait",
        name: "국사무쌍 13면 대기",
        japaneseName: "国士無双十三面待ち",
        category: "NORMAL",
        closedHan: 13,
        openHan: 0,
        isYakuman: true,
        yakumanMultiplier: 2,
        openType: "MENZEN_ONLY",
        description:
            "1, 9, 자패 13종을 모두 한 장씩 가진 상태에서 13종 어느 패로든 화료할 수 있는 국사무쌍의 특수 형태입니다.",
        exampleTiles: [
            "🀇",
            "🀏",
            "🀙",
            "🀡",
            "🀐",
            "🀘",
            "🀀",
            "🀁",
            "🀂",
            "🀃",
            "🀆",
            "🀅",
            "🀄",
            "🀄",
        ],
        notes: ["더블역만으로 계산합니다."],
    },
    {
        id: "suuankou",
        name: "스안커",
        japaneseName: "四暗刻",
        category: "NORMAL",
        closedHan: 13,
        openHan: 0,
        isYakuman: true,
        yakumanMultiplier: 1,
        openType: "MENZEN_ONLY",
        description: "안커 4개를 만들면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀇",
            "🀇",
            "🀙",
            "🀙",
            "🀙",
            "🀐",
            "🀐",
            "🀐",
            "🀄",
            "🀄",
            "🀄",
            "🀀",
            "🀀",
        ],
    },
    {
        id: "suuankou_tanki",
        name: "스안커 단기",
        japaneseName: "四暗刻単騎",
        category: "NORMAL",
        closedHan: 13,
        openHan: 0,
        isYakuman: true,
        yakumanMultiplier: 2,
        openType: "MENZEN_ONLY",
        description: "안커 4개를 완성한 상태에서 머리의 단기 대기로 화료하면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀇",
            "🀇",
            "🀙",
            "🀙",
            "🀙",
            "🀐",
            "🀐",
            "🀐",
            "🀄",
            "🀄",
            "🀄",
            "🀀",
            "🀀",
        ],
        notes: ["더블역만으로 계산합니다."],
    },
    {
        id: "daisangen",
        name: "대삼원",
        japaneseName: "大三元",
        category: "NORMAL",
        closedHan: 13,
        openHan: 13,
        isYakuman: true,
        yakumanMultiplier: 1,
        openType: "OPEN_ALLOWED",
        description: "백, 발, 중 삼원패를 모두 커쯔 또는 깡쯔로 만들면 성립합니다.",
        exampleTiles: [
            "🀆",
            "🀆",
            "🀆",
            "🀅",
            "🀅",
            "🀅",
            "🀄",
            "🀄",
            "🀄",
            "🀇",
            "🀈",
            "🀉",
            "🀀",
            "🀀",
        ],
    },
    {
        id: "shousuushi",
        name: "소사희",
        japaneseName: "小四喜",
        category: "NORMAL",
        closedHan: 13,
        openHan: 13,
        isYakuman: true,
        yakumanMultiplier: 1,
        openType: "OPEN_ALLOWED",
        description:
            "풍패 4종 중 3종을 커쯔로 만들고, 나머지 1종을 머리로 만들면 성립합니다.",
        exampleTiles: [
            "🀀",
            "🀀",
            "🀀",
            "🀁",
            "🀁",
            "🀁",
            "🀂",
            "🀂",
            "🀂",
            "🀃",
            "🀃",
            "🀇",
            "🀈",
            "🀉",
        ],
    },
    {
        id: "daisuushi",
        name: "대사희",
        japaneseName: "大四喜",
        category: "NORMAL",
        closedHan: 13,
        openHan: 13,
        isYakuman: true,
        yakumanMultiplier: 1,
        openType: "OPEN_ALLOWED",
        description: "풍패 4종을 모두 커쯔 또는 깡쯔로 만들면 성립합니다.",
        exampleTiles: [
            "🀀",
            "🀀",
            "🀀",
            "🀁",
            "🀁",
            "🀁",
            "🀂",
            "🀂",
            "🀂",
            "🀃",
            "🀃",
            "🀃",
            "🀆",
            "🀆",
        ],
    },
    {
        id: "tsuuiisou",
        name: "자일색",
        japaneseName: "字一色",
        category: "NORMAL",
        closedHan: 13,
        openHan: 13,
        isYakuman: true,
        yakumanMultiplier: 1,
        openType: "OPEN_ALLOWED",
        description: "자패만으로 화료하면 성립합니다.",
        exampleTiles: [
            "🀀",
            "🀀",
            "🀀",
            "🀁",
            "🀁",
            "🀁",
            "🀆",
            "🀆",
            "🀆",
            "🀄",
            "🀄",
            "🀄",
            "🀅",
            "🀅",
        ],
    },
    {
        id: "ryuuiisou",
        name: "녹일색",
        japaneseName: "緑一色",
        category: "NORMAL",
        closedHan: 13,
        openHan: 13,
        isYakuman: true,
        yakumanMultiplier: 1,
        openType: "OPEN_ALLOWED",
        description:
            "녹색 패로만 화료하면 성립합니다. 보통 삭수 2, 3, 4, 6, 8과 발패가 사용됩니다.",
        exampleTiles: [
            "🀑",
            "🀑",
            "🀑",
            "🀒",
            "🀓",
            "🀔",
            "🀕",
            "🀕",
            "🀕",
            "🀗",
            "🀗",
            "🀗",
            "🀅",
            "🀅",
        ],
    },
    {
        id: "chinroutou",
        name: "청노두",
        japaneseName: "清老頭",
        category: "NORMAL",
        closedHan: 13,
        openHan: 13,
        isYakuman: true,
        yakumanMultiplier: 1,
        openType: "OPEN_ALLOWED",
        description: "1과 9의 수패만으로 화료하면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀇",
            "🀇",
            "🀏",
            "🀏",
            "🀏",
            "🀙",
            "🀙",
            "🀙",
            "🀡",
            "🀡",
            "🀡",
            "🀐",
            "🀐",
        ],
    },
    {
        id: "suukantsu",
        name: "스깡쯔",
        japaneseName: "四槓子",
        category: "NORMAL",
        closedHan: 13,
        openHan: 13,
        isYakuman: true,
        yakumanMultiplier: 1,
        openType: "OPEN_ALLOWED",
        description: "깡쯔 4개를 만들면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀇",
            "🀇",
            "🀇",
            "🀙",
            "🀙",
            "🀙",
            "🀙",
            "🀐",
            "🀐",
            "🀐",
            "🀐",
            "🀆",
            "🀆",
        ],
    },
    {
        id: "chuurenpoutou",
        name: "구련보등",
        japaneseName: "九蓮宝燈",
        category: "NORMAL",
        closedHan: 13,
        openHan: 0,
        isYakuman: true,
        yakumanMultiplier: 1,
        openType: "MENZEN_ONLY",
        description:
            "한 종류의 수패로 1112345678999 형태를 만들고 같은 종류의 아무 패나 더해 화료하면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀇",
            "🀇",
            "🀈",
            "🀉",
            "🀊",
            "🀋",
            "🀌",
            "🀍",
            "🀎",
            "🀏",
            "🀏",
            "🀏",
            "🀋",
        ],
    },
    {
        id: "junsei_chuurenpoutou",
        name: "순정구련보등",
        japaneseName: "純正九蓮宝燈",
        category: "NORMAL",
        closedHan: 13,
        openHan: 0,
        isYakuman: true,
        yakumanMultiplier: 2,
        openType: "MENZEN_ONLY",
        description:
            "한 종류의 수패로 1112345678999 형태를 완성하고, 1~9 어느 패로도 화료 가능한 구련보등의 특수 형태입니다.",
        exampleTiles: [
            "🀇",
            "🀇",
            "🀇",
            "🀈",
            "🀉",
            "🀊",
            "🀋",
            "🀌",
            "🀍",
            "🀎",
            "🀏",
            "🀏",
            "🀏",
            "🀋",
        ],
        notes: ["더블역만으로 계산합니다."],
    },
    {
        id: "tenho",
        name: "천화",
        japaneseName: "天和",
        category: "NORMAL",
        closedHan: 13,
        openHan: 0,
        isYakuman: true,
        yakumanMultiplier: 1,
        openType: "MENZEN_ONLY",
        description: "친이 배패 직후 바로 화료하면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀈",
            "🀉",
            "🀋",
            "🀌",
            "🀍",
            "🀙",
            "🀚",
            "🀛",
            "🀐",
            "🀑",
            "🀒",
            "🀀",
            "🀀",
        ],
    },
    {
        id: "chiho",
        name: "지화",
        japaneseName: "地和",
        category: "NORMAL",
        closedHan: 13,
        openHan: 0,
        isYakuman: true,
        yakumanMultiplier: 1,
        openType: "MENZEN_ONLY",
        description: "자리가 첫 쯔모에서 아무 부름 없이 화료하면 성립합니다.",
        exampleTiles: [
            "🀇",
            "🀈",
            "🀉",
            "🀋",
            "🀌",
            "🀍",
            "🀙",
            "🀚",
            "🀛",
            "🀐",
            "🀑",
            "🀒",
            "🀀",
            "🀀",
        ],
    },
];